# Generated by Django 2.2 on 2020-10-26 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(default='', max_length=100)),
                ('vehicle_price', models.FloatField()),
                ('vehicle_brand', models.CharField(default='', max_length=60)),
                ('vehicle_model', models.CharField(default='', max_length=30)),
                ('vehicle_status', models.CharField(default='', max_length=30)),
                ('inventoryadmin_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAvailability',
            fields=[
                ('vehicle_availabilityId', models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False)),
                ('vehicle_availabilityStatus', models.CharField(default='', max_length=100)),
                ('vehicle_availabilityComments', models.FloatField()),
                ('vehicle_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiclemsapp.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchaseorder_Id', models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False)),
                ('purchaseorder_date', models.DateTimeField()),
                ('totalnumberordered', models.IntegerField()),
                ('purchaseorder_status', models.CharField(default='', max_length=30)),
                ('supplier_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_availabilityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiclemsapp.VehicleAvailability')),
                ('vehicle_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehiclemsapp.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='BillingOrder',
            fields=[
                ('billingorder_Id', models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False)),
                ('billingorder_price', models.FloatField()),
                ('billingorder_status', models.CharField(blank=True, max_length=30, null=True)),
                ('billingorder_date', models.DateTimeField()),
                ('purchaseorder_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiclemsapp.PurchaseOrder')),
            ],
        ),
    ]
