# Generated by Django 2.2 on 2020-10-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingorder',
            options={'verbose_name': 'BillingOrder', 'verbose_name_plural': 'BillingOrder'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'PurchaseOrder', 'verbose_name_plural': 'PurchaseOrder'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicle'},
        ),
        migrations.AlterModelOptions(
            name='vehicleavailability',
            options={'verbose_name': 'VehicleAvailability', 'verbose_name_plural': 'VehicleAvailability'},
        ),
    ]
