# Generated by Django 2.1.1 on 2020-11-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemsapp', '0003_auto_20201027_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='supplier_email',
            new_name='suppliercontact',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='inventoryadmin_email',
            new_name='inventoryadmincontact',
        ),
    ]
